/**
 * Stack live email round-trip smoke.
 *
 * Self-contained — does NOT depend on NanoClaw's running service.
 * Sends a real drop to kaitseng@seattleacademy.org, polls Gmail for the
 * reply, and runs Stack's handleInboundReply on it. Verifies that the
 * RFC 2822 Message-Id round-trips correctly and the rating + feedback
 * land in the in-script DB and vault.
 *
 *   1. Scrape one HN item, grade with qwen3:14b, enrich with Haiku.
 *   2. Persist to in-memory DB + tmp vault, mark sent with the Message-Id.
 *   3. Print the Message-Id and prompt to reply with `8 great test`.
 *   4. Poll Gmail every 15s (10 min budget) for a reply whose
 *      In-Reply-To header matches our Message-Id.
 *   5. Pass the reply body to handleInboundReply, then verify
 *      stack_ratings and the vault frontmatter.
 *
 * Usage:
 *   tsx scripts/stack-smoke-email.ts
 *
 * Requires:
 *   ~/.gmail-mcp/credentials.json fresh and authorized
 *   CLAUDE_CODE_OAUTH_TOKEN in the env (or ~/.claude/.credentials.json)
 *   ollama serving qwen3:14b at localhost:11434
 */

import Database from 'better-sqlite3';
import os from 'os';
import path from 'path';
import fs from 'fs';

import { google } from 'googleapis';
import { OAuth2Client } from 'google-auth-library';

import { applyStackSchema } from '../src/stack/db.js';
import { initVault, readDropFrontmatter } from '../src/stack/vault.js';
import { persistDrop } from '../src/stack/pipeline/confidence-gate.js';
import { markSent } from '../src/stack/pipeline/picker.js';
import { sendDropEmail } from '../src/stack/delivery/outbound.js';
import { wrapGmailClient } from '../src/stack/gmail.js';
import { handleInboundReply } from '../src/stack/delivery/inbound.js';
import type { Drop } from '../src/stack/types.js';

const SENDER = 'amazingkangaroofilms@gmail.com';
const RECIPIENT = 'kaitseng@seattleacademy.org';
const POLL_INTERVAL_MS = 15_000;
const POLL_BUDGET_MS = 10 * 60 * 1000;

function step(s: string): void {
  console.log(`\n=== ${s} ===`);
}

function buildAuthedGmail() {
  const credDir = path.join(os.homedir(), '.gmail-mcp');
  const keys = JSON.parse(fs.readFileSync(path.join(credDir, 'gcp-oauth.keys.json'), 'utf-8'));
  const tokens = JSON.parse(fs.readFileSync(path.join(credDir, 'credentials.json'), 'utf-8'));
  const client = keys.installed || keys.web || keys;
  const oauth2: OAuth2Client = new google.auth.OAuth2(client.client_id, client.client_secret, client.redirect_uris?.[0]);
  oauth2.setCredentials(tokens);
  oauth2.on('tokens', (newTokens) => {
    try {
      const cur = JSON.parse(fs.readFileSync(path.join(credDir, 'credentials.json'), 'utf-8'));
      Object.assign(cur, newTokens);
      fs.writeFileSync(path.join(credDir, 'credentials.json'), JSON.stringify(cur, null, 2));
    } catch {
      // non-fatal
    }
  });
  return google.gmail({ version: 'v1', auth: oauth2 });
}

async function pickAndPersist(db: Database.Database, vault: string): Promise<Drop> {
  // Hand-craft a Drop directly. Smoke-1 already proved Qwen grading + Haiku
  // enrichment work end-to-end; smoke-2's job is the email round-trip + the
  // RFC 2822 Message-Id matching on inbound replies. Skipping the LLM stages
  // here keeps the run deterministic (and short).
  const drop: Drop = {
    id: `drop_smoke_${Date.now()}`,
    bucket: 'foundation',
    name: 'DNS',
    tagline: 'How names become addresses',
    bodyHtml:
      '<p><strong>DNS</strong> — the system that turns human-readable names like <code>example.com</code> into the IP addresses computers actually use to connect.</p>' +
      '<p><strong>The mental model:</strong> a phone book for the internet. Your laptop asks a resolver "what\'s the address for <code>example.com</code>?" and gets back something like <code>93.184.216.34</code>.</p>' +
      '<p><strong>How it works (just enough):</strong> resolvers query a hierarchy — root servers know about <code>.com</code>, <code>.com</code> servers know about <code>example.com</code>, and so on. Caching at every layer keeps it fast.</p>' +
      '<p><em>(Smoke test drop — generated by scripts/stack-smoke-email.ts)</em></p>',
    bodyPlain:
      'DNS — How names become addresses.\n\nDNS turns human-readable names into IP addresses. A phone book for the internet.\n\n(Smoke test drop)',
    sourceUrl: 'https://en.wikipedia.org/wiki/Domain_Name_System',
    sourceFetchedAt: new Date().toISOString(),
    tags: ['networking', 'foundations'],
    confidence: 0.95,
    status: 'queued',
    vaultPath: '',
    createdAt: new Date().toISOString(),
  };
  console.log(`hand-crafted Drop: ${drop.name} (${drop.bucket})`);
  return persistDrop(db, vault, drop);
}

async function pollForReply(
  gmail: ReturnType<typeof google.gmail>,
  expectedMessageId: string,
): Promise<{ body: string; gmailInternalId: string }> {
  const start = Date.now();
  console.log(`polling for reply with In-Reply-To: ${expectedMessageId}`);
  console.log(`(every ${POLL_INTERVAL_MS / 1000}s, budget ${POLL_BUDGET_MS / 60_000}min)`);

  while (Date.now() - start < POLL_BUDGET_MS) {
    const list = await gmail.users.messages.list({
      userId: 'me',
      q: `from:${RECIPIENT} subject:"Re: Stack" newer_than:1h`,
      maxResults: 20,
    });
    const candidates = list.data.messages ?? [];
    for (const m of candidates) {
      if (!m.id) continue;
      const full = await gmail.users.messages.get({
        userId: 'me',
        id: m.id,
        format: 'full',
      });
      const headers = full.data.payload?.headers ?? [];
      const inReplyTo = headers.find((h) => h.name?.toLowerCase() === 'in-reply-to')?.value ?? '';
      if (inReplyTo !== expectedMessageId) continue;
      const body = extractTextBody(full.data.payload);
      console.log(`\nfound matching reply (gmail internal id ${m.id})`);
      console.log(`In-Reply-To: ${inReplyTo}`);
      console.log(`body preview: ${body.slice(0, 120)}`);
      return { body, gmailInternalId: m.id };
    }
    process.stdout.write('.');
    await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
  }
  throw new Error(`no matching reply within ${POLL_BUDGET_MS / 60_000}min`);
}

function extractTextBody(payload: any): string {
  if (!payload) return '';
  if (payload.mimeType === 'text/plain' && payload.body?.data) {
    return Buffer.from(payload.body.data, 'base64url').toString('utf-8');
  }
  if (Array.isArray(payload.parts)) {
    for (const part of payload.parts) {
      const got = extractTextBody(part);
      if (got) return got;
    }
  }
  if (payload.body?.data) {
    return Buffer.from(payload.body.data, 'base64url').toString('utf-8');
  }
  return '';
}

async function main(): Promise<void> {
  const startedAt = Date.now();

  step('Setup');
  const vault = fs.mkdtempSync(path.join(os.tmpdir(), 'stack-smoke-email-'));
  initVault(vault);
  const db = new Database(':memory:');
  applyStackSchema(db);
  console.log(`vault: ${vault}`);

  step('Persist hand-crafted Drop (LLM stages skipped — covered by smoke-1)');
  const drop = await pickAndPersist(db, vault);
  console.log(`\npersisted drop:`);
  console.log(`  id:         ${drop.id}`);
  console.log(`  name:       ${drop.name}`);
  console.log(`  bucket:     ${drop.bucket}`);
  console.log(`  vaultPath:  ${drop.vaultPath}`);

  step('Send drop email via real Gmail');
  const rawGmail = buildAuthedGmail();
  const gmailSender = wrapGmailClient(rawGmail);
  const messageId = await sendDropEmail(gmailSender, { from: SENDER, to: RECIPIENT }, drop);
  console.log(`messageId stored: ${messageId}`);
  if (!messageId.startsWith('<') || !messageId.endsWith('>')) {
    throw new Error(`messageId is not RFC 2822 Message-Id format (expected <...@...>): ${messageId}`);
  }
  markSent(db, drop.id, new Date().toISOString(), messageId);

  step('Wait for reply');
  console.log(`Reply to the email at ${RECIPIENT} with this exact body (one line):`);
  console.log(`\n  8 great test\n`);
  console.log(`Then come back. Polling starts now.`);

  const { body } = await pollForReply(rawGmail, messageId);

  step('Run handleInboundReply');
  const result = await handleInboundReply(db, vault, gmailSender, {
    addrs: { from: SENDER, to: RECIPIENT },
    threadMessageId: messageId,
    body,
  });
  console.log(`acked:  ${result.acked}`);
  console.log(`reason: ${result.reason}`);
  if (result.acked) {
    throw new Error(`numeric rating must NOT trigger an ack — got acked=${result.acked}`);
  }
  if (result.reason !== 'rating_silent') {
    throw new Error(`expected reason='rating_silent', got '${result.reason}'`);
  }

  step('Verify DB + vault');
  const ratingRow = db.prepare('SELECT * FROM stack_ratings WHERE drop_id=?').get(drop.id) as
    | { rating: number; feedback: string | null }
    | undefined;
  if (!ratingRow) throw new Error('no row in stack_ratings');
  console.log(`stack_ratings: rating=${ratingRow.rating} feedback=${JSON.stringify(ratingRow.feedback)}`);
  if (ratingRow.rating < 1 || ratingRow.rating > 10) {
    throw new Error(`rating out of range: ${ratingRow.rating}`);
  }

  const vaultFile = path.join(vault, drop.vaultPath);
  const fm = readDropFrontmatter(vaultFile);
  console.log(`vault frontmatter: rating=${fm.rating} feedback=${JSON.stringify(fm.feedback)} ratedAt=${fm.ratedAt}`);
  if (fm.rating !== ratingRow.rating) {
    throw new Error(`vault rating ${fm.rating} != db rating ${ratingRow.rating}`);
  }

  step('Result');
  console.log('SMOKE 2 PASSED — full email round-trip works against real Gmail.');
  console.log(`elapsed: ${((Date.now() - startedAt) / 1000).toFixed(1)}s`);
  console.log(`vault: ${vault}`);
}

main().catch((err) => {
  console.error('\n=== SMOKE FAILED ===');
  console.error(err);
  process.exit(1);
});
